core:
   logger_name: IoT Manager
   backend:
     kwargs:
      {mq_uri: 'inproc://iot/channels/rest',
logger_name: MQ IoT Channel, timeout: 2000, debug: False}

components:
   api:
    type: STANDALONE_PROCESS
    path: web.webrun
    start: start_app
    kwargs:
     {logger_name: IoT REST API, host: '0.0.0.0',
 port: 8101, mq_uri: core.mq_uri, debug: False}